services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    ports:
      - "3306:3306"
    restart: always
  irrigation-service:
    container_name: irrigation-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql:3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test123
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    depends_on:
      - mysql

volumes:
  mysql-volume:
    driver: local