spring:
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}/irrigation-service?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false
    properties:
      hibernate:
        show_sql: false

irrigation:
  alerting:
    email: ${alerting_email}