server:
  port: 8080

spring:
  application:
    name: irrigation-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test123
    url: jdbc:mysql://localhost:3306/irrigation-service?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
logging:
  file:
    name: irrigation-service.log
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [trace-id=%X{traceId}] [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [trace-id=%X{traceId}] [%t] %m%n"