server:
  port: 8080

spring:
  application:
    name: irrigation-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test123
    url: jdbc:mysql://localhost:3306/irrigation-service?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true

irrigation:
  scheduler:
    fixed-rate: 60000
    initial-delay: 5000
  api:
    base-url: "http://localhost:8080/api/sensor"
    response-timeout: 10
    retry:
      max-attempts: 3
      backoff: 1

logging:
  file:
    name: irrigation-service.log
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] %m%n"