INSERT INTO plot (id, code, area, crop_type) VALUES(1, 'PLOT-ALEX-218', 'Alexandria', 'grapes');
INSERT INTO plot (id, code, area, crop_type) VALUES(2, 'PLOT-ALEX-748', 'Alexandria', 'grapes');
INSERT INTO plot (id, code, area, crop_type) VALUES(3, 'PLOT-ALEX-778', 'Alexandria', 'watermelon');
INSERT INTO plot (id, code, area, crop_type) VALUES(4, 'PLOT-ALEX-8002', 'Alexandria', 'apple');
INSERT INTO plot (id, code, area, crop_type) VALUES(5, 'PLOT-ASSWAN-001', 'Asswan', 'sugarcane');
INSERT INTO plot (id, code, area, crop_type) VALUES(6, 'PLOT-ASSWAN-071', 'Asswan', 'sugarcane');
INSERT INTO plot (id, code, area, crop_type) VALUES(7, 'PLOT-ASSWAN-072', 'Asswan', 'tomato');
INSERT INTO plot (id, code, area, crop_type) VALUES(8, 'PLOT-ASSWAN-172', 'Asswan', 'tomato');
INSERT INTO plot (id, code, area, crop_type) VALUES(9, 'PLOT-ASSWAN-174', 'Asswan', 'watermelon');
INSERT INTO plot (id, code, area, crop_type) VALUES(10, 'PLOT-ASSWAN-002', 'Asswan', 'grapes');
INSERT INTO plot (id, code, area, crop_type) VALUES(11, 'PLOT-MENIA-998', 'AlMenia', 'sugarcane');
INSERT INTO plot (id, code, area, crop_type) VALUES(12, 'PLOT-MENIA-999', 'AlMenia', 'peach');
INSERT INTO plot (id, code, area, crop_type) VALUES(13, 'PLOT-MENIA-1000', 'AlMenia', 'bananas');
INSERT INTO plot (id, code, area, crop_type) VALUES(14, 'PLOT-ALEX-8003', 'Alexandria', 'bananas');
INSERT INTO plot (id, code, area, crop_type) VALUES(15, 'PLOT-ALEX-8013', 'Alexandria', 'peach');

INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(150, '16:00:00', '16:30:00', 1, 'IN_PROGRESS');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '16:35:00', '16:40:00', 1, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(150, '16:00:00', '16:30:00', 2, 'FAILED');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '16:40:00', '17:00:00', 3, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '09:00:00', '10:00:00', 4, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '09:00:00', '10:00:00', 5, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '16:05:00', '17:00:00', 6, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '16:30:00', '17:00:00', 7, 'DELETED');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '16:35:00', '17:00:00', 7, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '17:35:00', '19:00:00', 10, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '10:00:00', '13:00:00', 12, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '10:00:00', '13:00:00', 11, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(88, '11:00:00', '13:00:00', 11, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(100, '11:00:00', '13:00:00', 14, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(55, '13:00:00', '15:00:00', 14, 'READY');
INSERT INTO plot_irrigation_slot (amount_liters, start_time, end_time, plot_id, status) VALUES(150, '13:00:00', '15:00:00', 13, 'READY');
